// Video game data.
// The canonical source of truth is data/games/<id>.json (easy to edit by hand).
// When the app is served over HTTP the JSON files are fetched directly.
// When opened via file:// (where browsers block fetch), the FALLBACK copy below
// is used instead — keep it in sync with the JSON files.

window.BUNGO = window.BUNGO || {};

BUNGO.GAME_IDS = ["mario64","darksouls"];

BUNGO.GAMES_FALLBACK = {
  "mario64": {
    "id": "mario64",
    "name": "Super Mario 64",
    "tasks": [
      "Collect a Star in Bob-omb Battlefield",
      "Defeat King Bob-omb",
      "Collect 8 Red Coins in any level",
      "Collect 100 coins in a single level",
      "Ride a Koopa Shell",
      "Ground pound a wooden post",
      "Break open a wooden box",
      "Talk to a Toad",
      "Find a secret Star in Peach's Castle",
      "Unlock a cannon",
      "Launch yourself from a cannon",
      "Defeat the Whomp King",
      "Collect a Star in Whomp's Fortress",
      "Slide down Cool, Cool Mountain",
      "Race the penguin down the slide",
      "Carry the baby penguin to its mother",
      "Collect a Star in Jolly Roger Bay",
      "Open a treasure chest",
      "Collect a Star in Lethal Lava Land",
      "Ground pound the Chain Chomp's post",
      "Collect a Star in Shifting Sand Land",
      "Enter the pyramid",
      "Collect a Star in Dire, Dire Docks",
      "Collect a Star in Snowman's Land",
      "Freeze an enemy",
      "Collect a Star in Wet-Dry World",
      "Change the water level",
      "Collect a Star in Tall, Tall Mountain",
      "Collect a Star in Tiny-Huge Island",
      "Become tiny or huge",
      "Collect a Star in Tick Tock Clock",
      "Collect a Star in Rainbow Ride",
      "Defeat Bowser",
      "Collect a Star in Hazy Maze Cave",
      "Ride Dorrie the dinosaur",
      "Collect a Star in Big Boo's Haunt",
      "Defeat Big Boo",
      "Collect a Star in the secret aquarium",
      "Collect 50 coins in Peach's Castle",
      "Jump into a painting",
      "Wall kick to reach a high ledge",
      "Perform a triple jump",
      "Long jump across a gap",
      "Backflip onto a higher platform",
      "Find a hidden 1-Up",
      "Reach the castle rooftop",
      "Collect a red coin inside the castle",
      "Ride the magic carpet",
      "Break a brick while invisible",
      "Fly with the Wing Cap",
      "Collect 8 red coins in the sky",
      "Sink underwater with the Metal Cap",
      "Collect a Star in Bowser in the Dark World",
      "Collect a Star in Bowser in the Fire Sea",
      "Collect a Star in Bowser in the Sky",
      "Throw Bowser into a mine",
      "Collect 120 Power Stars"
    ]
  },
  "darksouls": {
    "id": "darksouls",
    "name": "Dark Souls",
    "tasks": [
      "Ring the first Bell of Awakening",
      "Ring the second Bell of Awakening",
      "Kindle a bonfire",
      "Become human at a bonfire",
      "Join a covenant",
      "Obtain the Lordvessel",
      "Return to the Undead Asylum",
      "Enter the Painted World of Ariamis",
      "Reach Anor Londo",
      "Lower the water in New Londo Ruins",
      "Cross the narrow beams in Sen's Fortress",
      "Survive the swinging axes in Sen's Fortress",
      "Free Big Hat Logan from Sen's Fortress",
      "Rescue Lautrec from his cell",
      "Rescue Siegmeyer of Catarina",
      "Obtain the Rite of Kindling",
      "Obtain the Peculiar Doll",
      "Find the Rusted Iron Ring",
      "Upgrade a weapon to +10",
      "Parry an enemy",
      "Backstab an enemy",
      "Kick an enemy off a ledge",
      "Summon an NPC phantom",
      "Defeat an invading NPC phantom",
      "Open the shortcut to Lost Izalith",
      "Farm a soft humanity from enemies",
      "Die to a Mimic",
      "Get cursed",
      "Defeat the Asylum Demon",
      "Defeat the Taurus Demon",
      "Defeat the Bell Gargoyles",
      "Defeat the Capra Demon",
      "Defeat the Gaping Dragon",
      "Defeat Chaos Witch Quelaag",
      "Defeat the Iron Golem",
      "Defeat Ornstein and Smough",
      "Defeat Seath the Scaleless",
      "Defeat the Four Kings",
      "Defeat Gravelord Nito",
      "Defeat the Bed of Chaos",
      "Defeat Gwyn, Lord of Cinder",
      "Defeat the Moonlight Butterfly",
      "Defeat Great Grey Wolf Sif",
      "Defeat Pinwheel",
      "Defeat the Stray Demon",
      "Defeat the Demon Firesage",
      "Defeat the Ceaseless Discharge",
      "Defeat the Centipede Demon",
      "Defeat Crossbreed Priscilla",
      "Defeat Dark Sun Gwyndolin",
      "Defeat the Hydra in Darkroot Basin",
      "Defeat the Hydra in Ash Lake",
      "Defeat a Titanite Demon",
      "Defeat a Black Knight",
      "Defeat Havel the Rock",
      "Defeat the Undead Dragon",
      "Defeat the Hellkite Dragon",
      "Defeat the Sanctuary Guardian",
      "Defeat Knight Artorias",
      "Defeat Manus, Father of the Abyss",
      "Defeat Black Dragon Kalameet",
      "Collect the Dagger",
      "Collect the Bandit's Knife",
      "Collect the Parrying Dagger",
      "Collect Priscilla's Dagger",
      "Collect the Ghost Blade",
      "Collect the Dark Silver Tracer",
      "Collect the Shortsword",
      "Collect the Longsword",
      "Collect the Broadsword",
      "Collect the Balder Side Sword",
      "Collect the Sunlight Straight Sword",
      "Collect Astora's Straight Sword",
      "Collect the Silver Knight Straight Sword",
      "Collect the Drake Sword",
      "Collect the Crystal Straight Sword",
      "Collect the Barbed Straight Sword",
      "Collect the Dark Sword",
      "Collect the Broken Straight Sword",
      "Collect the Straight Sword Hilt",
      "Collect the Bastard Sword",
      "Collect the Claymore",
      "Collect the Flamberge",
      "Collect the Great Lord Greatsword",
      "Collect the Man-serpent Greatsword",
      "Collect the Crystal Greatsword",
      "Collect the Black Knight Sword",
      "Collect the Moonlight Greatsword",
      "Collect the Greatsword of Artorias",
      "Collect the Abyss Greatsword",
      "Collect the Obsidian Greatsword",
      "Collect the Stone Greatsword",
      "Collect the Zweihander",
      "Collect the Greatsword",
      "Collect the Demon Great Machete",
      "Collect the Dragon Greatsword",
      "Collect the Black Knight Greatsword",
      "Collect the Scimitar",
      "Collect the Falchion",
      "Collect the Shotel",
      "Collect the Painting Guardian Sword",
      "Collect Quelaag's Furysword",
      "Collect the Gold Tracer",
      "Collect the Jagged Ghost Blade",
      "Collect the Server",
      "Collect the Murakumo",
      "Collect the Gravelord Sword",
      "Collect the Uchigatana",
      "Collect the Iaito",
      "Collect the Washing Pole",
      "Collect the Chaos Blade",
      "Collect the Rapier",
      "Collect the Estoc",
      "Collect the Mail Breaker",
      "Collect Ricard's Rapier",
      "Collect Velka's Rapier",
      "Collect the Hand Axe",
      "Collect the Battle Axe",
      "Collect the Butcher Knife",
      "Collect the Gargoyle Tail Axe",
      "Collect the Golem Axe",
      "Collect the Crescent Axe",
      "Collect the Greataxe",
      "Collect the Demon's Greataxe",
      "Collect the Dragon King Greataxe",
      "Collect the Stone Greataxe",
      "Collect the Black Knight Greataxe",
      "Collect the Club",
      "Collect the Reinforced Club",
      "Collect the Mace",
      "Collect the Morning Star",
      "Collect the Warpick",
      "Collect the Pickaxe",
      "Collect the Blacksmith Giant Hammer",
      "Collect the Hammer of Vamos",
      "Collect the Blacksmith Hammer",
      "Collect the Large Club",
      "Collect the Great Club",
      "Collect the Dragon Tooth",
      "Collect Smough's Hammer",
      "Collect Grant",
      "Collect the Demon's Great Hammer",
      "Collect the Spear",
      "Collect the Winged Spear",
      "Collect the Pike",
      "Collect the Partizan",
      "Collect the Four-Pronged Plow",
      "Collect the Demon's Spear",
      "Collect the Silver Knight Spear",
      "Collect the Channeler's Trident",
      "Collect the Dragonslayer Spear",
      "Collect the Moonlight Butterfly Horn",
      "Collect the Halberd",
      "Collect the Lucerne",
      "Collect the Scythe",
      "Collect the Great Scythe",
      "Collect the Lifehunt Scythe",
      "Collect the Titanite Catch Pole",
      "Collect the Black Knight Halberd",
      "Collect the Giant's Halberd",
      "Collect the Gargoyle's Halberd",
      "Collect the Whip",
      "Collect the Notched Whip",
      "Collect the Guardian Tail",
      "Collect the Caestus",
      "Collect the Claw",
      "Collect the Dragon Bone Fist",
      "Collect the Dark Hand",
      "Collect the Short Bow",
      "Collect the Longbow",
      "Collect the Composite Bow",
      "Collect the Black Bow of Pharis",
      "Collect the Darkmoon Bow",
      "Collect the Dragonslayer Greatbow",
      "Collect Gough's Greatbow",
      "Collect the Light Crossbow",
      "Collect the Heavy Crossbow",
      "Collect the Sniper Crossbow",
      "Collect the Avelyn",
      "Collect the Sorcerer's Catalyst",
      "Collect the Oolacile Ivory Catalyst",
      "Collect the Tin Banishment Catalyst",
      "Collect Beatrice's Catalyst",
      "Collect Logan's Catalyst",
      "Collect the Tin Crystallization Catalyst",
      "Collect the Demon's Catalyst",
      "Collect the Izalith Catalyst",
      "Collect the Manus Catalyst",
      "Collect the Talisman",
      "Collect the Canvas Talisman",
      "Collect the Thorolund Talisman",
      "Collect the Ivory Talisman",
      "Collect the Sunlight Talisman",
      "Collect the Darkmoon Talisman",
      "Collect Velka's Talisman",
      "Collect the Pyromancy Flame",
      "Collect the Ascended Pyromancy Flame",
      "Collect the Small Leather Shield",
      "Collect the Buckler",
      "Collect the Target Shield",
      "Collect the Caduceus Round Shield",
      "Collect the Warrior's Round Shield",
      "Collect the Red and White Round Shield",
      "Collect the Plank Shield",
      "Collect the Leather Shield",
      "Collect the Cracked Round Shield",
      "Collect the Heater Shield",
      "Collect the Knight Shield",
      "Collect the Balder Shield",
      "Collect the Grass Crest Shield",
      "Collect the Crest Shield",
      "Collect the Dragon Crest Shield",
      "Collect the Spider Shield",
      "Collect the Sunlight Shield",
      "Collect the Iron Round Shield",
      "Collect the Silver Knight Shield",
      "Collect the Black Knight Shield",
      "Collect the Tower Kite Shield",
      "Collect the Wooden Shield",
      "Collect the Large Leather Shield",
      "Collect the Bloodshield",
      "Collect Sanctus",
      "Collect the Effigy Shield",
      "Collect the Caduceus Kite Shield",
      "Collect the Hollow Soldier Shield",
      "Collect the Pierce Shield",
      "Collect the East-West Shield",
      "Collect the Eagle Shield",
      "Collect the Tower Shield",
      "Collect the Stone Greatshield",
      "Collect the Black Iron Greatshield",
      "Collect the Bonewheel Shield",
      "Collect the Cleansing Greatshield",
      "Collect the Giant Shield",
      "Collect the Greatshield of Artorias",
      "Collect Havel's Greatshield"
    ]
  }
};

BUNGO.games = {};

// Loads each registered game. Tries the JSON file first, falls back to the
// embedded copy when fetch is unavailable (e.g. file:// in Chrome/Edge).
BUNGO.loadGames = async function () {
  for (const id of BUNGO.GAME_IDS) {
    let data = null;
    try {
      const res = await fetch("data/games/" + id + ".json");
      if (res.ok) data = await res.json();
    } catch (e) {
      /* fall through to fallback */
    }
    if (!data) data = BUNGO.GAMES_FALLBACK[id];
    BUNGO.games[id] = data;
  }
  return BUNGO.games;
};

BUNGO.getTasks = function (id) {
  return (BUNGO.games[id] && BUNGO.games[id].tasks) || [];
};

BUNGO.getGameName = function (id) {
  return (BUNGO.games[id] && BUNGO.games[id].name) || id;
};
